# Project Aims

Maladaptive exercise is a common, debilitating symptom across eating disorders (ED). Up to 40% of individuals with bulimia nervosa and 80% of those with anorexia nervosa experience driven exercise. Driven exercise relates to high levels of ED symptoms and poor ED treatment outcomes, and has been purported to be an early ED symptom via retrospective reports. Among those with EDs, maladaptive exercise is associated with: increased risk for suicidal behavior; poor treatment outcome, disorder prognosis, and quality of life[@adamsExerciseDependenceReview1998; @dallegraveCompulsiveExerciseControl2008] obsessive-compulsive traits and symptoms[@shroffFeaturesAssociatedExcessive2006; @davisPrevalenceHighlevelExercise1997; @davisAnorexiaNervosaExcessive2006]; anxiety[@shroffFeaturesAssociatedExcessive2006; @holtkampContributionAnxietyFood2004]; perfectionism[@shroffFeaturesAssociatedExcessive2006]; body dissatisfaction [@brewertonComparisonEatingDisorder1995]; reward dependence[@dallegraveCompulsiveExerciseControl2008]; dietary restraint[@dallegraveCompulsiveExerciseControl2008; @holtkampContributionAnxietyFood2004]; anhedonia [@davisSensitivityRewardingEffects2002]; and hypoleptinemia [@holtkampElevatedPhysicalActivity2003; @holtkampPhysicalActivityRestlessness2006]. Further, maladaptive exercise has been hypothesized to be both compulsive[@meyerCompulsiveExerciseEating2011] and/or addictive [@cookExerciseAddictionCompulsive2014] in nature. 

Preliminary studies suggest a potential role of genetic factors influencing risk for this eating disorder feature. The most recently published genome-wide association study (GWAS) of AN from the Eating Disorders Workgroup of the Psychiatric Genomics Consortium demonstrated a positive genetic correlation (*r~g~* = .17) with accelerometer-measured PA [@anorexianervosageneticsinitiativeGenomewideAssociationStudy2019], suggesting that some of the same factors that increase risk for AN are also operative in determining general PA levels. Further, preliminary findings examining polygenic prediction of eating disorder symptoms in the ALSPAC cohort supports the assertion that compulsive predisposition may impact the symptom of driven exercise, specifically. When examining obsessive-compulsive disorder (OCD) and anorexia nervosa (AN) polygenic scores, along with a transdiagnostic OCD/AN polygenic score as predictors of a variety of eating disorder and anxiety-related symtpoms in early-to-mid adolescence, driven exercise was the only eating disorder symptom that was positively predicted (at at least one age and gender time point) by all three polygenic scores[@yilmazPredictingEatingDisorder2022]

Overall, existing research points towards compulsivity and general propensity to exercise as potential risk factors for driven exercise. Further, driven exercise may be an early indicator of high eating disorder risk, as an additional investigation in the ALSPAC cohort found that both exercise for weight loss and driven exercise groups at age 14 were demonstrated higher levels of other ED behaviors (binge eating, fasting, purging) at age 16[@schaumbergProspectiveAssociationsDriven2022].
  

Enhanced understanding of driven exercise is critical as the eating disorder field grapples with designing appropriate interventions for those at risk for, in treatment for, or in remission from eating disorders. High levels of physical activity are frequently associated with positive mental and physical health outcomes[@chekroudAssociationPhysicalExercise2018; @vankimVigorousPhysicalActivity2013; @deslandesExerciseMentalHealth2009], and exercise (planned, structured, repetitive PA)[@caspersenPhysicalActivityExercise1985] is increasingly prescribed as a component of mental health treatment. Exercise also evidences some therapeutic benefit in ED treatment, including preventing loss of bone density, enhancing cognitive functioning, self-regulation, social engagement, and mood regulation, and reducing discomfort during future eating episodes[@achamrahPhysicalActivityPatients2016; @hausenblasCanExerciseTreat2008; @calogeroPracticeProcessHealthy2004]. As a result of the complex relationship between exercise and EDs, more sophisticated research on this phenotype is needed. At present, we know relatively little about the etiology of DEx, including potential genetic influences on the symptom, its relationship to premorbid activity levels, or how to manage this symptom. In addition, we do not understand factors that contribute to the substantial variability in physical activity among those with eating disorders, and why only a portion of individuals present with driven exercise. Given the critical need to improve treatment for individuals with eating disorders, and even more-so for those who engage in driven exercise, improving our understanding of risk for this symptom is paramount.


In the current line of research, we are extend a longitudinal investigation of exercise for weight loss and driven exercise across a larger developmental window (ages 14-24) in the ALSPAC Cohort.

Aims of the research include:

```{r, echo = FALSE, message = FALSE}

library(dplyr)
library(knitr)
library(kableExtra)

aims_tbl <- data.frame(
  Aim = c("1", "2", "3"),
  Goal = c("Identify and characterize the physical activity trajectories from late childhood through emerging adulthood in ALSPAC and capture associations with driven exercise and eating disorder risk.", "Determine the strength of DEx as a predictor of eating disorder pathology", "Demonstrate the influence of genomic risk factors on DEx"),
  Hypothesis = c("High levels of activity in childhood and early adolescence will associate with both DEx and ED risk in adolescence", "DEx will present early in the course of EDs, with peak age of onset in early-to-mid adolescence, and will predict ED onset and maintenance beyond other risk factors (e.g. dieting, thin-deal internalization)", "'Anthropometric/Activity' and 'Compulsivity' genomic risk factors will be identified and will predict DEx" )
)

knitr::kable(aims_tbl) %>% 
    kable_paper(full_width = F) %>% 
    column_spec(1, bold = T, border_right = T) %>% 
    column_spec(2, background = 'gray', color = 'white')
```
