# Cognitive Eating Disorder Features

+-----------------------------+------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| Construct                   | Age              | Measure                                                                                                                                                                                    | ED Cognitive Symptom Diagnostic Criteria Cutoffs                                                             |
+:============================+:=================+:===========================================================================================================================================================================================+:=============================================================================================================+
| Body Image Discrepancy      | 10 (128 months)  | Stunkard Figure Rating Scale                                                                                                                                                               |                                                                                                              |
+-----------------------------+------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| Thin ideal internalization  | 14 (167 months)  | IBSS-R appearance ideals rated on a 5-point Likert scale from 'strongly agree' to 'strongly disagree.'                                                                                     |                                                                                                              |
+-----------------------------+------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| Pressure to Lose Weight     | 14 (167 months)  | Perceived Sociocultural Pressure Scale.                                                                                                                                                    |                                                                                                              |
+-----------------------------+------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| Pressure to Increase Muscle | 14 (167 months)  | Perceived Sociocultural Pressure Scale.                                                                                                                                                    |                                                                                                              |
+-----------------------------+------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| External Eating             | 14 (167 months)  | Dutch Eating Behavior Questionnaire (DEBQ)                                                                                                                                                 |                                                                                                              |
+-----------------------------+------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| Restrained Eating           | 14 (167 months)  | Dutch Eating Behavior Questionnaire (DEBQ)                                                                                                                                                 |                                                                                                              |
+-----------------------------+------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| Emotional Eating            | 14 (167 months)  | Dutch Eating Behavior Questionnaire (DEBQ)                                                                                                                                                 |                                                                                                              |
+-----------------------------+------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| Weight/Shape Concern        | 14 (167 months)  | Assessed using 2-items from the McKnight risk survey asking how how happy participants are with their bodies and if weight has made a difference in how they have felt about their bodies  | **'Very unhappy' with weight and shape or weight making 'A lot/quite a lot' of difference in how one feels** |
+-----------------------------+------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| Body Dissatisfaction        | 14 (167 months), | At wave 14, Satisfaction with body parts is ranked on a 5-point Likert scale, from 'extremely satisfied' to 'extremely dissatisfied' with higher values indicating higher dissatisfaction. | **Average score of 'moderately dissatisfied' or higher**                                                     |
|                             |                  |                                                                                                                                                                                            |                                                                                                              |
|                             | 18 (222 months)  | At waves 18 and 24, body satisfaction is ranked on how happy person is with the way their body looked in the past year on a Likert scale from 'very unhappy' to 'very happy'.              | **Average score of 'A little happy' or lower**                                                               |
|                             |                  |                                                                                                                                                                                            |                                                                                                              |
|                             | 24 (288 months)  |                                                                                                                                                                                            |                                                                                                              |
+-----------------------------+------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| Dieting                     | 14 (167 months), | Frequency during the past year young person went on a diet to lose weight/keep from gaining weight.                                                                                        | **Dieting reported in the past year 'several times' or more**                                                |
|                             |                  |                                                                                                                                                                                            |                                                                                                              |
|                             | 16 (198 months), |                                                                                                                                                                                            |                                                                                                              |
|                             |                  |                                                                                                                                                                                            |                                                                                                              |
|                             | 18 (222 months)  |                                                                                                                                                                                            |                                                                                                              |
+-----------------------------+------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| Fear of Weight Gain         | 14 (167 months), | Participants reported the degree they worried about gaining a little weight (two pounds) in the past year.                                                                                 | **Fear of weight gain endorsed 'a lot' or 'all the time'**                                                   |
|                             |                  |                                                                                                                                                                                            |                                                                                                              |
|                             | 24 (288 months)  |                                                                                                                                                                                            |                                                                                                              |
+-----------------------------+------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| Weight Intentions           | 14 (167 months), | Participants reported what they are trying to do with their weight.                                                                                                                        | **Weight loss intentions reported**                                                                          |
|                             |                  |                                                                                                                                                                                            |                                                                                                              |
|                             | 18 (222 months)  |                                                                                                                                                                                            |                                                                                                              |
+-----------------------------+------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| Weight Perception           | 14 (167 months), | Participants reported their perception of their weight.                                                                                                                                    |                                                                                                              |
|                             |                  |                                                                                                                                                                                            |                                                                                                              |
|                             | 18 (222 months)  |                                                                                                                                                                                            |                                                                                                              |
+-----------------------------+------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| Weight Valuation            | 18 (222 months)  | Participants reported the degree to which their weight has made a difference to how they feel about themselves.                                                                            | **Weight valuation reported 'somewhat' or more**                                                             |
+-----------------------------+------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| Feeling Fat                 | 24 (288 months)  | Participant reported the frequency that they have felt fat in the past year.                                                                                                               | **Feeling fat reported 'sometimes' or more**                                                                 |
+-----------------------------+------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+

## Body Discrepancy

Body dissatisfaction at age 10.5 years was assessed using gender-appropriate Stunkard figure rating scales (FRS) [@shermanDevelopmentValidationBody1995]. The FRS presents participants with either 5 female or male figures (dependent on the sex of the participant) of different weights and heights and asks which figure the participant most resembles and which figure the participant desires to resemble.

### Scoring

Responses for figures varying in weight were scored as 'very thin', 'thin', 'average', 'fat', or 'very fat' while figures varying in height were scored as 'very short', 'short', 'average', 'tall', or 'very tall'. A body discrepancy score is generated by subtracting the ideal body weight/height chosen from the current perceived body weight/height (higher scores indicate higher body dissatisfaction).

### Key Variables

`body_percept.128` Respondent's perception of his/her body shape at age 10

`body_desire.128` Respondent's desired body shape at age 10

## Thin-ideal Internalization

Thin-ideal internalization at age 14 was assessed using the Ideal-Body Stereotype Scale-Revised (IBSS-R) [@sticeTestDualPathway1996] Girls and boys were both asked six questions, three of which were the same and three of which were gender-specific, assessing the perceived attractiveness of same-sex individuals based on physical characteristics (e.g. being 'lean', 'tall', 'petite').

### Scoring

Items are rated on a 5-point Likert scale ranging from 'Strongly Disagree' (0) to 'Strongly Agree' (4) [@calzoSexualOrientationDisparities2018]. The ten items are averaged to form an overall thin-ideal internalization score.

### Key Variables

`ti_mean.167` Mean thin-ideal internalization score at age 14

`ti_mean.167_NAs` Percent of variables missing from the thin-ideal internalization measure

## Pressure to Lose Weight/Pressure to Increase Muscle

Pressure to lose weight and to increase muscle were both assessed at age 14 using an adapted version of the Perceived Sociocultural Pressure Scale [@sticeModelingEatingPathology1998]. Participants were asked the extent to which they have felt pressures from friends, family, partners, and the media to lose weight and increase their muscle size. Female participants were only asked about pressures relating to weight while male participants were asked about both pressures relating to weight and muscle.

### Scoring

Response options for both pressure to lose weight and increase muscle were 'Not at all' (1), 'A little' (2), 'Quite a lot' (3), and 'A lot' (4). Scores for each assessment are averaged to form an average score of pressure to lose weight and an average score of pressure to increase muscle.

### Key Variables

`pressure_lose_sum.167` Sum of pressure to lose weight scale at age 14

`pressure_lose_sum.167_NAs` Percent of variables missing from the pressure to lose weight scale

`pressure_musc_sum.167` Sum of pressure to increase muscle scale at age 14

`pressure_musc_sum.167_NAs` Percent of variables missing from the pressure to gain muscle scale

## Restrained Eating, External Eating, and Emotional Eating

Restrictive Eating, External Eating, and Emotional Eating were assessed at child age 14 years by the Dutch Eating Behavior Questionnaire (DEBQ) [@vanstrienDutchEatingBehavior1986]. Restrained eating addressed purposefully restricting intake regarding weight concerns. External eating addressed the likelihood of a participant eating due to external stimuli like the sight and smell of the food, regardless of the participant's hunger level. Finally, emotional eating addressed how often the participant ate excessively when they experienced different emotional states.

### Scoring

Depending on the phrasing of the items, responses were either asked on a scale of 'Yes, usually want to eat more' (1), 'Sometimes want to eat more' (2), or 'No, not at all' (3) or on a scale of 'Never' (1), 'Occasionally' (2), 'Sometimes' (3), or 'Frequently' (4). Scores are summed with greater scores indicating a greater likelihood of engagement with restrained eating, external eating, or emotional eating.

### Key Variables

`restraint_sum.167` Sum of the restrained eating items at age 14

`restraint_sum.167_NAs` Percent of variables missing from the restrained eating subscale

`ext_eat_sum.167` Sum of the external eating items at age 14

`ext_eat_sum.167_NAs` Percent of variables missing from the external eating subscale

`emo_eat_sum.167` Sum of the emotional eating items at age 14

`emo_eat_sum.167_NAs` Percent of variables missing from the emotional eating subscale

`emo_eat_sum_d.167` Sum of dichotomous responses for emotional eating items

`emo_eat_sum_d.167_NAs` Percent of variables missing from the dichotomous emotional eating subscale

## Shape and Weight Concern

Shape and Weight concern were assessed at age 14 using items from the McNight Risk Factor Survey, which assesses risk and protective factors for the development of eating disorders in preadolescence and adolescent girls [@shisslakDevelopmentEvaluationMcKnight1999]. The two items taken from the McKnight Survey were:

1.  'In the past year, how happy have you been with the way your body looks?'

2.  'In the past year, how much has your weight made a difference to how you feel about yourself?'

### Scoring

A 4-point Likert scale was used (from 'very unhappy' (1) or 'not at all' (1) to 'very happy' (4) or 'a lot/all the time' (4)) to assess weight and shape concern. The two questions were summed to generate a continuous score.

### Key Variables

`wt_shape_concern.167` Continuous sum of weight and shape concern items at age 14

`wt_shape_concern.167_NAs` Percent of variables missing from the weight and shape items

## Body Dissatisfaction

Body Dissatisfaction was assessed at ages 14, 18, and 24. An 11-item scale adapted from the satisfaction and dissatisfaction with body parts scale [@sticeProspectiveTestDualpathway2001], which has been used in several previous studies involving the ALSPAC Cohort [@bornioliAdolescentBodyDissatisfaction2019] [@bornioliBodyDissatisfactionPredicts2021] [@schaumbergAnxietyDisorderSymptoms2019] [@schaumbergProspectiveAssociationsChildhood2021], was given at Wave 14. Among the 11 items, one item differs between the sexes (satisfaction with 'breasts' is specified for girls and 'build' for boys). Two items address overall body satisfaction with weight and figure, and the remaining items evaluate satisfaction with specific body parts.

Participants were not asked about body satisfaction at age 16. At Wave 18 and 24, participants completed 1 item that addressed happiness levels regarding weight and shape in the past year.

### Scoring

At age 14, responses are graded on a 5-point Likert scale from 'Extremely Satisfied' (1) to 'Extremely Dissatisfied' (5).

At age 18, participants were presented with four responses ranging from 'Very unhappy' (1) to 'Very happy' (4). At age 24, participants were given 5 response options ranging from 'Not at all happy' (1) to 'completely happy' (5).

Body dissatisfaction was scored using the mean of all 11 items, with higher scores indicating greater body dissatisfaction.

### Key Variables

`body_sat_mean.167` Body dissatisfaction mean score at age 14

`body_sat_mean.167_NAs` Percent of variables missing from the body dissatisfaction measure at age 14

`body_sat.222` How happy respondent has been with way body looks in past year at age 18

`body_sat.288` Degree respondent has been happy with way their body looks or weighs at age 24

## Dieting

Dieting was assessed at ages 14, 16, and 18 years.

To assess dieting, participants were asked a set of questions regarding dieting strategies to lose or keep from gaining weight and actual weight loss in the past year. While these items are original to the ALSPAC study, thesy have been used in multiple studies to assess the overall level of dieting in adolescents [@micaliAdolescentEatingDisorder2015] [@jonesMisreportingEnergyIntake2021]. The question consists of multiple parts with the aim to learn the extent of dieting a respondent has taken part in. The first part of the question aims to find the type of diet(s) and length of time the participant has engaged in said diet(s) and the second part asks about weight lost during the diet and possible weight gain succeeding the diet.

### Scoring

When asked if the participant has gone on a diet in the past year, responses range from 'Always on a diet' (1) to 'never' (5). If respondent selects any answer other than 'never', they are then prompted to respond how long they engaged in the diet(s) ('less than a week', '1-3 weeks', '1-3 months', or '3 or 4 months') and the type of diet(s) they used.

The participant also answers how many pounds they lost while on to the diet(s) and, if they did lose weight, if they gained any of the weight back after the diet ('No, did not regain any of the weight', 'Gained back a little of the weight", 'Gained back most of the weight', 'Gained back all of the weight', or 'put on more than I lost').

### Key Variables

`diet_freq.167` Frequency respondent went on a diet to lose weight or keep from gaining weight during the past year at age 14

`diet_length_2.167` Length of time respondent was on a diet at age 14

`diet_freq.198` Frequency respondent went on a diet to lose weight or keep from gaining weight during the past year at age 16

`diet_length_2.198` Length of time respondent was on a diet at age 16

`diet_lost_2.198` How much weight respondent lost on diet at age 16

`diet_wt_gain_2.198` How much weight (if any) respondent gained back after diet at age 16

`diet_freq.222` Frequency respondent went on a diet to lose weight or keep from gaining weight during the past year at age 18

`diet_length_2.222` Length of time respondent was on a diet at age 18

`diet_wt_loss_2.222` How much weight respondent lost on diet at age 18

`diet_wt_gain_2.222` How much weight (if any) respondent gained back after diet at age 18

## Fear of Weight Gain

Fear of weight gain was assessed at Wave 14 and Wave 24 via a single item asking the degree to which participants have worried about gaining a little weight (as little as one kilo).

### Scoring

At age 14, participants scored their fear of weight gain on a 4-point Likert response scale: 'Not at all' (1), 'A little' (2), 'A lot' (3), and 'All the time' (4).

At age 24, participants scored their fear of weight gain on a 4-point Likert response scale: 'Not at all' (1), 'A little' (2), 'A lot' (3), and 'Pretty much all the time' (4).

### Key Variables

`fear_wtgain.167` Degree to which respondent has worried about gaining a little weight in the past year at age 14

`fear_wtgain.288` Degree to which respondent has worried about gaining a little weight in the past year at age 24

## Weight Intentions, Perception, and Valuation

Weight intentions, perception, and valuation were all asked with the pretense that there is no correct answer and participants should answer how they think. Weight intentions and perception were assessed at ages 14 and 18 while weight valuation was only asked at age 18.

At both Wave 14 and Wave 18, Weight intentions was assessed in 1 item that asked participants about what they intend to do with their weight. Weight perception asks participants to describe their current weight.

Weight valuation, which was asked at age 18, was also a 1-item question that asked how weight has made a difference in how the participant sees oneself.

### Scoring

Weight intentions was scored using 4 response options: 'I am not trying to do anything about my weight', 'Stay the same', 'Gain weight', or 'Lose weight'.

Weight perception gave a range of 5 responses from 'Very underweight' to 'Very overweight'.

Weight valuation was scored on a 5-point Likert scale from 'Not at all' (1) to 'A lot' (5).

### Key Variables

`wt_intent.167` Respondent's intent with weight at age 14

`wt_perception.167` Description of respondent's current weight at age 14

`wt_intent.222` Respondent's intent with weight at age 18

`wt_perception.222` Description of respondent's current weight at age 18

`wt_valuation.222` Degree to which respondent's weight has made difference to how feel about self in past year at age 18

## Feeling Fat

Individuals were asked at age 24 how often they 'felt fat' in the past year.

### Scoring

Response options were 'Never' (0), 'A little' (1), 'Sometimes' (2), 'A lot' (3), and 'Always' (4).

### Key Variables

`feel_fat.288` How much respondent has 'felt fat' in the past year at age 24
